### PR TITLE
Add device to readme, add exception for unreachable host

### PR DESCRIPTION
**Pull request by alexandrehassan**
Got my router (Bell Giga Hub) working with this project so added it to the readme as well as its auth method.

When testing other things noticed that the `pre-commit` for flake8 has been moved.

Also added an exception for the `login()` method that prompts user to double check host address.

### CODE REVIEW

**Review by iMicknl — APPROVED** [review]

**Comment by iMicknl** [comment]
Thanks @alexandrehassan! Good improvements. Unfortunately I haven't been able to work on this library for a long time, mainly due to the fact that I don't own the device anymore and due to time constraints.

**Comment by iMicknl** [comment]
@alexandrehassan I will be working on modernizing this (+ the HA repo) a bit in the coming weeks. Can you rebase this PR so I can merge it?

**Comment by alexandrehassan** [comment]
> @alexandrehassan I will be working on modernizing this (+ the HA repo) a bit in the coming weeks. Can you rebase this PR so I can merge it?

Unsure how to do that

**Comment by iMicknl** [comment]
These changes have been added to the repo by other PRs. Thanks for your contribution!

**Pull request closed without merging**
