### PR TITLE
Add Bell (Home Hub 4000) on the supported devices list

### PR DESCRIPTION
**Pull request by dapiced**
| Sagemcom F@st XXXX    | Bell (Home Hub 4000) | md5                   | username: admin, password: "" |

### CODE REVIEW

**Comment by dapiced** [comment]
its working for me. At least login, reboot functions and also your sample script.

**Review by iMicknl — APPROVED** [review]

**Review by dapiced — COMMENTED** [review]
Add the model number

**Comment by dapiced** [comment]
The Model number has been given by my Collegue Benoit Rochon Aka "Ben la Menace" ;)

Thanks Ben !

**Comment by dapiced** [comment]
im done wirh the pull request, do i need to merge by myself or it on you side ?

**Pull request merged**
